name: Generate Sitemap

on:
  push:
    branches:
      - main

jobs:
  sitemap:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Generate sitemap
        uses: cicirello/generate-sitemap@v1
        with:
          base-url-path: https://weapptesters.com

      - name: Commit sitemap
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add sitemap.xml
          git commit -m "Update sitemap" || echo "No changes"
          git push
